#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALDoAnHoChieu
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HoChieu")]
	public partial class HoChieuModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDangKyHoChieu(DangKyHoChieu instance);
    partial void UpdateDangKyHoChieu(DangKyHoChieu instance);
    partial void DeleteDangKyHoChieu(DangKyHoChieu instance);
    partial void InsertTrangThai(TrangThai instance);
    partial void UpdateTrangThai(TrangThai instance);
    partial void DeleteTrangThai(TrangThai instance);
    partial void InsertDanToc(DanToc instance);
    partial void UpdateDanToc(DanToc instance);
    partial void DeleteDanToc(DanToc instance);
    partial void InsertGioiTinh(GioiTinh instance);
    partial void UpdateGioiTinh(GioiTinh instance);
    partial void DeleteGioiTinh(GioiTinh instance);
    partial void InsertHoChieu(HoChieu instance);
    partial void UpdateHoChieu(HoChieu instance);
    partial void DeleteHoChieu(HoChieu instance);
    partial void InsertNgheNghiep(NgheNghiep instance);
    partial void UpdateNgheNghiep(NgheNghiep instance);
    partial void DeleteNgheNghiep(NgheNghiep instance);
    partial void InsertPhuong(Phuong instance);
    partial void UpdatePhuong(Phuong instance);
    partial void DeletePhuong(Phuong instance);
    partial void InsertQuan(Quan instance);
    partial void UpdateQuan(Quan instance);
    partial void DeleteQuan(Quan instance);
    partial void InsertQuocGia(QuocGia instance);
    partial void UpdateQuocGia(QuocGia instance);
    partial void DeleteQuocGia(QuocGia instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertTinh(Tinh instance);
    partial void UpdateTinh(Tinh instance);
    partial void DeleteTinh(Tinh instance);
    partial void InsertTonGiao(TonGiao instance);
    partial void UpdateTonGiao(TonGiao instance);
    partial void DeleteTonGiao(TonGiao instance);
    #endregion
		
		public HoChieuModelDataContext() : 
				base(global::DALDoAnHoChieu.Properties.Settings.Default.HoChieuConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HoChieuModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HoChieuModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HoChieuModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HoChieuModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DangKyHoChieu> DangKyHoChieus
		{
			get
			{
				return this.GetTable<DangKyHoChieu>();
			}
		}
		
		public System.Data.Linq.Table<TrangThai> TrangThais
		{
			get
			{
				return this.GetTable<TrangThai>();
			}
		}
		
		public System.Data.Linq.Table<DanToc> DanTocs
		{
			get
			{
				return this.GetTable<DanToc>();
			}
		}
		
		public System.Data.Linq.Table<GioiTinh> GioiTinhs
		{
			get
			{
				return this.GetTable<GioiTinh>();
			}
		}
		
		public System.Data.Linq.Table<HoChieu> HoChieus
		{
			get
			{
				return this.GetTable<HoChieu>();
			}
		}
		
		public System.Data.Linq.Table<NgheNghiep> NgheNghieps
		{
			get
			{
				return this.GetTable<NgheNghiep>();
			}
		}
		
		public System.Data.Linq.Table<Phuong> Phuongs
		{
			get
			{
				return this.GetTable<Phuong>();
			}
		}
		
		public System.Data.Linq.Table<Quan> Quans
		{
			get
			{
				return this.GetTable<Quan>();
			}
		}
		
		public System.Data.Linq.Table<QuocGia> QuocGias
		{
			get
			{
				return this.GetTable<QuocGia>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<Tinh> Tinhs
		{
			get
			{
				return this.GetTable<Tinh>();
			}
		}
		
		public System.Data.Linq.Table<TonGiao> TonGiaos
		{
			get
			{
				return this.GetTable<TonGiao>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KiemTraDangNhap")]
		public ISingleResult<KiemTraDangNhapResult> KiemTraDangNhap([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, password);
			return ((ISingleResult<KiemTraDangNhapResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangKyHoChieu")]
	public partial class DangKyHoChieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDangKyMoi;
		
		private string _HoTen;
		
		private System.DateTime _NgaySinh;
		
		private string _QuocGiaNoiSinh;
		
		private int _Tinh;
		
		private string _SoCMND;
		
		private System.DateTime _NgayCapCMND;
		
		private int _NoiCapCMND;
		
		private int _DanToc;
		
		private int _TonGiao;
		
		private string _SDT;
		
		private string _Email;
		
		private int _TinhThuongTru;
		
		private int _QuanThuongTru;
		
		private int _PhuongThuongTru;
		
		private string _SoNhaThuongTru;
		
		private System.Nullable<int> _TinhTamTru;
		
		private System.Nullable<int> _PhuongTamTru;
		
		private System.Nullable<int> _QuanTamTru;
		
		private string _SoNhaTamTru;
		
		private int _NgheNghiep;
		
		private string _TenCoQuan;
		
		private string _DiaChiCoQuan;
		
		private string _TenCha;
		
		private string _TenMe;
		
		private System.Nullable<System.DateTime> _NgaySinhCha;
		
		private System.Nullable<System.DateTime> _NgaySinhMe;
		
		private string _TenVoChong;
		
		private System.Nullable<System.DateTime> _NgaySinhVoChong;
		
		private System.Nullable<int> _GioiTinh;
		
		private int _TrangThai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDangKyMoiChanging(int value);
    partial void OnMaDangKyMoiChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnQuocGiaNoiSinhChanging(string value);
    partial void OnQuocGiaNoiSinhChanged();
    partial void OnTinhChanging(int value);
    partial void OnTinhChanged();
    partial void OnSoCMNDChanging(string value);
    partial void OnSoCMNDChanged();
    partial void OnNgayCapCMNDChanging(System.DateTime value);
    partial void OnNgayCapCMNDChanged();
    partial void OnNoiCapCMNDChanging(int value);
    partial void OnNoiCapCMNDChanged();
    partial void OnDanTocChanging(int value);
    partial void OnDanTocChanged();
    partial void OnTonGiaoChanging(int value);
    partial void OnTonGiaoChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTinhThuongTruChanging(int value);
    partial void OnTinhThuongTruChanged();
    partial void OnQuanThuongTruChanging(int value);
    partial void OnQuanThuongTruChanged();
    partial void OnPhuongThuongTruChanging(int value);
    partial void OnPhuongThuongTruChanged();
    partial void OnSoNhaThuongTruChanging(string value);
    partial void OnSoNhaThuongTruChanged();
    partial void OnTinhTamTruChanging(System.Nullable<int> value);
    partial void OnTinhTamTruChanged();
    partial void OnPhuongTamTruChanging(System.Nullable<int> value);
    partial void OnPhuongTamTruChanged();
    partial void OnQuanTamTruChanging(System.Nullable<int> value);
    partial void OnQuanTamTruChanged();
    partial void OnSoNhaTamTruChanging(string value);
    partial void OnSoNhaTamTruChanged();
    partial void OnNgheNghiepChanging(int value);
    partial void OnNgheNghiepChanged();
    partial void OnTenCoQuanChanging(string value);
    partial void OnTenCoQuanChanged();
    partial void OnDiaChiCoQuanChanging(string value);
    partial void OnDiaChiCoQuanChanged();
    partial void OnTenChaChanging(string value);
    partial void OnTenChaChanged();
    partial void OnTenMeChanging(string value);
    partial void OnTenMeChanged();
    partial void OnNgaySinhChaChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChaChanged();
    partial void OnNgaySinhMeChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhMeChanged();
    partial void OnTenVoChongChanging(string value);
    partial void OnTenVoChongChanged();
    partial void OnNgaySinhVoChongChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhVoChongChanged();
    partial void OnGioiTinhChanging(System.Nullable<int> value);
    partial void OnGioiTinhChanged();
    partial void OnTrangThaiChanging(int value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public DangKyHoChieu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDangKyMoi", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaDangKyMoi
		{
			get
			{
				return this._MaDangKyMoi;
			}
			set
			{
				if ((this._MaDangKyMoi != value))
				{
					this.OnMaDangKyMoiChanging(value);
					this.SendPropertyChanging();
					this._MaDangKyMoi = value;
					this.SendPropertyChanged("MaDangKyMoi");
					this.OnMaDangKyMoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuocGiaNoiSinh", DbType="NVarChar(5)")]
		public string QuocGiaNoiSinh
		{
			get
			{
				return this._QuocGiaNoiSinh;
			}
			set
			{
				if ((this._QuocGiaNoiSinh != value))
				{
					this.OnQuocGiaNoiSinhChanging(value);
					this.SendPropertyChanging();
					this._QuocGiaNoiSinh = value;
					this.SendPropertyChanged("QuocGiaNoiSinh");
					this.OnQuocGiaNoiSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tinh", DbType="Int NOT NULL")]
		public int Tinh
		{
			get
			{
				return this._Tinh;
			}
			set
			{
				if ((this._Tinh != value))
				{
					this.OnTinhChanging(value);
					this.SendPropertyChanging();
					this._Tinh = value;
					this.SendPropertyChanged("Tinh");
					this.OnTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCMND", DbType="NVarChar(20)")]
		public string SoCMND
		{
			get
			{
				return this._SoCMND;
			}
			set
			{
				if ((this._SoCMND != value))
				{
					this.OnSoCMNDChanging(value);
					this.SendPropertyChanging();
					this._SoCMND = value;
					this.SendPropertyChanged("SoCMND");
					this.OnSoCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapCMND", DbType="Date NOT NULL")]
		public System.DateTime NgayCapCMND
		{
			get
			{
				return this._NgayCapCMND;
			}
			set
			{
				if ((this._NgayCapCMND != value))
				{
					this.OnNgayCapCMNDChanging(value);
					this.SendPropertyChanging();
					this._NgayCapCMND = value;
					this.SendPropertyChanged("NgayCapCMND");
					this.OnNgayCapCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiCapCMND", DbType="Int NOT NULL")]
		public int NoiCapCMND
		{
			get
			{
				return this._NoiCapCMND;
			}
			set
			{
				if ((this._NoiCapCMND != value))
				{
					this.OnNoiCapCMNDChanging(value);
					this.SendPropertyChanging();
					this._NoiCapCMND = value;
					this.SendPropertyChanged("NoiCapCMND");
					this.OnNoiCapCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanToc", DbType="Int NOT NULL")]
		public int DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this.OnDanTocChanging(value);
					this.SendPropertyChanging();
					this._DanToc = value;
					this.SendPropertyChanged("DanToc");
					this.OnDanTocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TonGiao", DbType="Int NOT NULL")]
		public int TonGiao
		{
			get
			{
				return this._TonGiao;
			}
			set
			{
				if ((this._TonGiao != value))
				{
					this.OnTonGiaoChanging(value);
					this.SendPropertyChanging();
					this._TonGiao = value;
					this.SendPropertyChanged("TonGiao");
					this.OnTonGiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(20)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(MAX)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhThuongTru", DbType="Int NOT NULL")]
		public int TinhThuongTru
		{
			get
			{
				return this._TinhThuongTru;
			}
			set
			{
				if ((this._TinhThuongTru != value))
				{
					this.OnTinhThuongTruChanging(value);
					this.SendPropertyChanging();
					this._TinhThuongTru = value;
					this.SendPropertyChanged("TinhThuongTru");
					this.OnTinhThuongTruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuanThuongTru", DbType="Int NOT NULL")]
		public int QuanThuongTru
		{
			get
			{
				return this._QuanThuongTru;
			}
			set
			{
				if ((this._QuanThuongTru != value))
				{
					this.OnQuanThuongTruChanging(value);
					this.SendPropertyChanging();
					this._QuanThuongTru = value;
					this.SendPropertyChanged("QuanThuongTru");
					this.OnQuanThuongTruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuongThuongTru", DbType="Int NOT NULL")]
		public int PhuongThuongTru
		{
			get
			{
				return this._PhuongThuongTru;
			}
			set
			{
				if ((this._PhuongThuongTru != value))
				{
					this.OnPhuongThuongTruChanging(value);
					this.SendPropertyChanging();
					this._PhuongThuongTru = value;
					this.SendPropertyChanged("PhuongThuongTru");
					this.OnPhuongThuongTruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNhaThuongTru", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string SoNhaThuongTru
		{
			get
			{
				return this._SoNhaThuongTru;
			}
			set
			{
				if ((this._SoNhaThuongTru != value))
				{
					this.OnSoNhaThuongTruChanging(value);
					this.SendPropertyChanging();
					this._SoNhaThuongTru = value;
					this.SendPropertyChanged("SoNhaThuongTru");
					this.OnSoNhaThuongTruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTamTru", DbType="Int")]
		public System.Nullable<int> TinhTamTru
		{
			get
			{
				return this._TinhTamTru;
			}
			set
			{
				if ((this._TinhTamTru != value))
				{
					this.OnTinhTamTruChanging(value);
					this.SendPropertyChanging();
					this._TinhTamTru = value;
					this.SendPropertyChanged("TinhTamTru");
					this.OnTinhTamTruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuongTamTru", DbType="Int")]
		public System.Nullable<int> PhuongTamTru
		{
			get
			{
				return this._PhuongTamTru;
			}
			set
			{
				if ((this._PhuongTamTru != value))
				{
					this.OnPhuongTamTruChanging(value);
					this.SendPropertyChanging();
					this._PhuongTamTru = value;
					this.SendPropertyChanged("PhuongTamTru");
					this.OnPhuongTamTruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuanTamTru", DbType="Int")]
		public System.Nullable<int> QuanTamTru
		{
			get
			{
				return this._QuanTamTru;
			}
			set
			{
				if ((this._QuanTamTru != value))
				{
					this.OnQuanTamTruChanging(value);
					this.SendPropertyChanging();
					this._QuanTamTru = value;
					this.SendPropertyChanged("QuanTamTru");
					this.OnQuanTamTruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNhaTamTru", DbType="NVarChar(MAX)")]
		public string SoNhaTamTru
		{
			get
			{
				return this._SoNhaTamTru;
			}
			set
			{
				if ((this._SoNhaTamTru != value))
				{
					this.OnSoNhaTamTruChanging(value);
					this.SendPropertyChanging();
					this._SoNhaTamTru = value;
					this.SendPropertyChanged("SoNhaTamTru");
					this.OnSoNhaTamTruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgheNghiep", DbType="Int NOT NULL")]
		public int NgheNghiep
		{
			get
			{
				return this._NgheNghiep;
			}
			set
			{
				if ((this._NgheNghiep != value))
				{
					this.OnNgheNghiepChanging(value);
					this.SendPropertyChanging();
					this._NgheNghiep = value;
					this.SendPropertyChanged("NgheNghiep");
					this.OnNgheNghiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCoQuan", DbType="NVarChar(50)")]
		public string TenCoQuan
		{
			get
			{
				return this._TenCoQuan;
			}
			set
			{
				if ((this._TenCoQuan != value))
				{
					this.OnTenCoQuanChanging(value);
					this.SendPropertyChanging();
					this._TenCoQuan = value;
					this.SendPropertyChanged("TenCoQuan");
					this.OnTenCoQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiCoQuan", DbType="NVarChar(MAX)")]
		public string DiaChiCoQuan
		{
			get
			{
				return this._DiaChiCoQuan;
			}
			set
			{
				if ((this._DiaChiCoQuan != value))
				{
					this.OnDiaChiCoQuanChanging(value);
					this.SendPropertyChanging();
					this._DiaChiCoQuan = value;
					this.SendPropertyChanged("DiaChiCoQuan");
					this.OnDiaChiCoQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCha", DbType="NVarChar(50)")]
		public string TenCha
		{
			get
			{
				return this._TenCha;
			}
			set
			{
				if ((this._TenCha != value))
				{
					this.OnTenChaChanging(value);
					this.SendPropertyChanging();
					this._TenCha = value;
					this.SendPropertyChanged("TenCha");
					this.OnTenChaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMe", DbType="NVarChar(50)")]
		public string TenMe
		{
			get
			{
				return this._TenMe;
			}
			set
			{
				if ((this._TenMe != value))
				{
					this.OnTenMeChanging(value);
					this.SendPropertyChanging();
					this._TenMe = value;
					this.SendPropertyChanged("TenMe");
					this.OnTenMeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinhCha", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinhCha
		{
			get
			{
				return this._NgaySinhCha;
			}
			set
			{
				if ((this._NgaySinhCha != value))
				{
					this.OnNgaySinhChaChanging(value);
					this.SendPropertyChanging();
					this._NgaySinhCha = value;
					this.SendPropertyChanged("NgaySinhCha");
					this.OnNgaySinhChaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinhMe", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinhMe
		{
			get
			{
				return this._NgaySinhMe;
			}
			set
			{
				if ((this._NgaySinhMe != value))
				{
					this.OnNgaySinhMeChanging(value);
					this.SendPropertyChanging();
					this._NgaySinhMe = value;
					this.SendPropertyChanged("NgaySinhMe");
					this.OnNgaySinhMeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVoChong", DbType="NVarChar(50)")]
		public string TenVoChong
		{
			get
			{
				return this._TenVoChong;
			}
			set
			{
				if ((this._TenVoChong != value))
				{
					this.OnTenVoChongChanging(value);
					this.SendPropertyChanging();
					this._TenVoChong = value;
					this.SendPropertyChanged("TenVoChong");
					this.OnTenVoChongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinhVoChong", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinhVoChong
		{
			get
			{
				return this._NgaySinhVoChong;
			}
			set
			{
				if ((this._NgaySinhVoChong != value))
				{
					this.OnNgaySinhVoChongChanging(value);
					this.SendPropertyChanging();
					this._NgaySinhVoChong = value;
					this.SendPropertyChanged("NgaySinhVoChong");
					this.OnNgaySinhVoChongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Int")]
		public System.Nullable<int> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int NOT NULL")]
		public int TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TrangThai")]
	public partial class TrangThai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTrangThai;
		
		private string _TenTrangThai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTrangThaiChanging(int value);
    partial void OnMaTrangThaiChanged();
    partial void OnTenTrangThaiChanging(string value);
    partial void OnTenTrangThaiChanged();
    #endregion
		
		public TrangThai()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTrangThai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTrangThai
		{
			get
			{
				return this._MaTrangThai;
			}
			set
			{
				if ((this._MaTrangThai != value))
				{
					this.OnMaTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._MaTrangThai = value;
					this.SendPropertyChanged("MaTrangThai");
					this.OnMaTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTrangThai", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TenTrangThai
		{
			get
			{
				return this._TenTrangThai;
			}
			set
			{
				if ((this._TenTrangThai != value))
				{
					this.OnTenTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TenTrangThai = value;
					this.SendPropertyChanged("TenTrangThai");
					this.OnTenTrangThaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanToc")]
	public partial class DanToc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDanToc;
		
		private string _TenDanToc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDanTocChanging(int value);
    partial void OnMaDanTocChanged();
    partial void OnTenDanTocChanging(string value);
    partial void OnTenDanTocChanged();
    #endregion
		
		public DanToc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDanToc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDanToc
		{
			get
			{
				return this._MaDanToc;
			}
			set
			{
				if ((this._MaDanToc != value))
				{
					this.OnMaDanTocChanging(value);
					this.SendPropertyChanging();
					this._MaDanToc = value;
					this.SendPropertyChanged("MaDanToc");
					this.OnMaDanTocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDanToc", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TenDanToc
		{
			get
			{
				return this._TenDanToc;
			}
			set
			{
				if ((this._TenDanToc != value))
				{
					this.OnTenDanTocChanging(value);
					this.SendPropertyChanging();
					this._TenDanToc = value;
					this.SendPropertyChanged("TenDanToc");
					this.OnTenDanTocChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GioiTinh")]
	public partial class GioiTinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaGioiTinh;
		
		private string _TenGioiTinh;
		
		private EntitySet<HoChieu> _HoChieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGioiTinhChanging(int value);
    partial void OnMaGioiTinhChanged();
    partial void OnTenGioiTinhChanging(string value);
    partial void OnTenGioiTinhChanged();
    #endregion
		
		public GioiTinh()
		{
			this._HoChieus = new EntitySet<HoChieu>(new Action<HoChieu>(this.attach_HoChieus), new Action<HoChieu>(this.detach_HoChieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGioiTinh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaGioiTinh
		{
			get
			{
				return this._MaGioiTinh;
			}
			set
			{
				if ((this._MaGioiTinh != value))
				{
					this.OnMaGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._MaGioiTinh = value;
					this.SendPropertyChanged("MaGioiTinh");
					this.OnMaGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGioiTinh", DbType="NVarChar(10)")]
		public string TenGioiTinh
		{
			get
			{
				return this._TenGioiTinh;
			}
			set
			{
				if ((this._TenGioiTinh != value))
				{
					this.OnTenGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._TenGioiTinh = value;
					this.SendPropertyChanged("TenGioiTinh");
					this.OnTenGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GioiTinh_HoChieu", Storage="_HoChieus", ThisKey="MaGioiTinh", OtherKey="GioiTinh")]
		public EntitySet<HoChieu> HoChieus
		{
			get
			{
				return this._HoChieus;
			}
			set
			{
				this._HoChieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoChieus(HoChieu entity)
		{
			this.SendPropertyChanging();
			entity.GioiTinh1 = this;
		}
		
		private void detach_HoChieus(HoChieu entity)
		{
			this.SendPropertyChanging();
			entity.GioiTinh1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoChieu")]
	public partial class HoChieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SoHoChieu;
		
		private int _QuocGia;
		
		private string _HoTen;
		
		private string _QuocTich;
		
		private System.DateTime _NgaySinh;
		
		private int _NoiSinh;
		
		private System.Nullable<int> _GioiTinh;
		
		private string _SoCMND;
		
		private System.DateTime _NgayCap;
		
		private System.DateTime _NgayHetHan;
		
		private int _NoiCap;
		
		private int _MaDangKy;
		
		private EntityRef<GioiTinh> _GioiTinh1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoHoChieuChanging(string value);
    partial void OnSoHoChieuChanged();
    partial void OnQuocGiaChanging(int value);
    partial void OnQuocGiaChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnQuocTichChanging(string value);
    partial void OnQuocTichChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnNoiSinhChanging(int value);
    partial void OnNoiSinhChanged();
    partial void OnGioiTinhChanging(System.Nullable<int> value);
    partial void OnGioiTinhChanged();
    partial void OnSoCMNDChanging(string value);
    partial void OnSoCMNDChanged();
    partial void OnNgayCapChanging(System.DateTime value);
    partial void OnNgayCapChanged();
    partial void OnNgayHetHanChanging(System.DateTime value);
    partial void OnNgayHetHanChanged();
    partial void OnNoiCapChanging(int value);
    partial void OnNoiCapChanged();
    partial void OnMaDangKyChanging(int value);
    partial void OnMaDangKyChanged();
    #endregion
		
		public HoChieu()
		{
			this._GioiTinh1 = default(EntityRef<GioiTinh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHoChieu", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SoHoChieu
		{
			get
			{
				return this._SoHoChieu;
			}
			set
			{
				if ((this._SoHoChieu != value))
				{
					this.OnSoHoChieuChanging(value);
					this.SendPropertyChanging();
					this._SoHoChieu = value;
					this.SendPropertyChanged("SoHoChieu");
					this.OnSoHoChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuocGia", DbType="Int NOT NULL")]
		public int QuocGia
		{
			get
			{
				return this._QuocGia;
			}
			set
			{
				if ((this._QuocGia != value))
				{
					this.OnQuocGiaChanging(value);
					this.SendPropertyChanging();
					this._QuocGia = value;
					this.SendPropertyChanged("QuocGia");
					this.OnQuocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(35) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuocTich", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string QuocTich
		{
			get
			{
				return this._QuocTich;
			}
			set
			{
				if ((this._QuocTich != value))
				{
					this.OnQuocTichChanging(value);
					this.SendPropertyChanging();
					this._QuocTich = value;
					this.SendPropertyChanged("QuocTich");
					this.OnQuocTichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiSinh", DbType="Int NOT NULL")]
		public int NoiSinh
		{
			get
			{
				return this._NoiSinh;
			}
			set
			{
				if ((this._NoiSinh != value))
				{
					this.OnNoiSinhChanging(value);
					this.SendPropertyChanging();
					this._NoiSinh = value;
					this.SendPropertyChanged("NoiSinh");
					this.OnNoiSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Int")]
		public System.Nullable<int> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					if (this._GioiTinh1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCMND", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SoCMND
		{
			get
			{
				return this._SoCMND;
			}
			set
			{
				if ((this._SoCMND != value))
				{
					this.OnSoCMNDChanging(value);
					this.SendPropertyChanging();
					this._SoCMND = value;
					this.SendPropertyChanged("SoCMND");
					this.OnSoCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCap", DbType="Date NOT NULL")]
		public System.DateTime NgayCap
		{
			get
			{
				return this._NgayCap;
			}
			set
			{
				if ((this._NgayCap != value))
				{
					this.OnNgayCapChanging(value);
					this.SendPropertyChanging();
					this._NgayCap = value;
					this.SendPropertyChanged("NgayCap");
					this.OnNgayCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHetHan", DbType="Date NOT NULL")]
		public System.DateTime NgayHetHan
		{
			get
			{
				return this._NgayHetHan;
			}
			set
			{
				if ((this._NgayHetHan != value))
				{
					this.OnNgayHetHanChanging(value);
					this.SendPropertyChanging();
					this._NgayHetHan = value;
					this.SendPropertyChanged("NgayHetHan");
					this.OnNgayHetHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiCap", DbType="Int NOT NULL")]
		public int NoiCap
		{
			get
			{
				return this._NoiCap;
			}
			set
			{
				if ((this._NoiCap != value))
				{
					this.OnNoiCapChanging(value);
					this.SendPropertyChanging();
					this._NoiCap = value;
					this.SendPropertyChanged("NoiCap");
					this.OnNoiCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDangKy", DbType="Int NOT NULL")]
		public int MaDangKy
		{
			get
			{
				return this._MaDangKy;
			}
			set
			{
				if ((this._MaDangKy != value))
				{
					this.OnMaDangKyChanging(value);
					this.SendPropertyChanging();
					this._MaDangKy = value;
					this.SendPropertyChanged("MaDangKy");
					this.OnMaDangKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GioiTinh_HoChieu", Storage="_GioiTinh1", ThisKey="GioiTinh", OtherKey="MaGioiTinh", IsForeignKey=true)]
		public GioiTinh GioiTinh1
		{
			get
			{
				return this._GioiTinh1.Entity;
			}
			set
			{
				GioiTinh previousValue = this._GioiTinh1.Entity;
				if (((previousValue != value) 
							|| (this._GioiTinh1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GioiTinh1.Entity = null;
						previousValue.HoChieus.Remove(this);
					}
					this._GioiTinh1.Entity = value;
					if ((value != null))
					{
						value.HoChieus.Add(this);
						this._GioiTinh = value.MaGioiTinh;
					}
					else
					{
						this._GioiTinh = default(Nullable<int>);
					}
					this.SendPropertyChanged("GioiTinh1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NgheNghiep")]
	public partial class NgheNghiep : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNgheNghiep;
		
		private string _TenNgheNghiep;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNgheNghiepChanging(int value);
    partial void OnMaNgheNghiepChanged();
    partial void OnTenNgheNghiepChanging(string value);
    partial void OnTenNgheNghiepChanged();
    #endregion
		
		public NgheNghiep()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNgheNghiep", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNgheNghiep
		{
			get
			{
				return this._MaNgheNghiep;
			}
			set
			{
				if ((this._MaNgheNghiep != value))
				{
					this.OnMaNgheNghiepChanging(value);
					this.SendPropertyChanging();
					this._MaNgheNghiep = value;
					this.SendPropertyChanged("MaNgheNghiep");
					this.OnMaNgheNghiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNgheNghiep", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNgheNghiep
		{
			get
			{
				return this._TenNgheNghiep;
			}
			set
			{
				if ((this._TenNgheNghiep != value))
				{
					this.OnTenNgheNghiepChanging(value);
					this.SendPropertyChanging();
					this._TenNgheNghiep = value;
					this.SendPropertyChanged("TenNgheNghiep");
					this.OnTenNgheNghiepChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phuong")]
	public partial class Phuong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhuong;
		
		private string _TenPhuong;
		
		private string _Loai;
		
		private int _MaQuan;
		
		private EntityRef<Quan> _Quan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhuongChanging(int value);
    partial void OnMaPhuongChanged();
    partial void OnTenPhuongChanging(string value);
    partial void OnTenPhuongChanged();
    partial void OnLoaiChanging(string value);
    partial void OnLoaiChanged();
    partial void OnMaQuanChanging(int value);
    partial void OnMaQuanChanged();
    #endregion
		
		public Phuong()
		{
			this._Quan = default(EntityRef<Quan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhuong", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaPhuong
		{
			get
			{
				return this._MaPhuong;
			}
			set
			{
				if ((this._MaPhuong != value))
				{
					this.OnMaPhuongChanging(value);
					this.SendPropertyChanging();
					this._MaPhuong = value;
					this.SendPropertyChanged("MaPhuong");
					this.OnMaPhuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhuong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenPhuong
		{
			get
			{
				return this._TenPhuong;
			}
			set
			{
				if ((this._TenPhuong != value))
				{
					this.OnTenPhuongChanging(value);
					this.SendPropertyChanging();
					this._TenPhuong = value;
					this.SendPropertyChanged("TenPhuong");
					this.OnTenPhuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="NVarChar(50)")]
		public string Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this.OnLoaiChanging(value);
					this.SendPropertyChanging();
					this._Loai = value;
					this.SendPropertyChanged("Loai");
					this.OnLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuan", DbType="Int NOT NULL")]
		public int MaQuan
		{
			get
			{
				return this._MaQuan;
			}
			set
			{
				if ((this._MaQuan != value))
				{
					if (this._Quan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaQuanChanging(value);
					this.SendPropertyChanging();
					this._MaQuan = value;
					this.SendPropertyChanged("MaQuan");
					this.OnMaQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Quan_Phuong", Storage="_Quan", ThisKey="MaQuan", OtherKey="MaQuan", IsForeignKey=true)]
		public Quan Quan
		{
			get
			{
				return this._Quan.Entity;
			}
			set
			{
				Quan previousValue = this._Quan.Entity;
				if (((previousValue != value) 
							|| (this._Quan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Quan.Entity = null;
						previousValue.Phuongs.Remove(this);
					}
					this._Quan.Entity = value;
					if ((value != null))
					{
						value.Phuongs.Add(this);
						this._MaQuan = value.MaQuan;
					}
					else
					{
						this._MaQuan = default(int);
					}
					this.SendPropertyChanged("Quan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Quan")]
	public partial class Quan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaQuan;
		
		private string _TenQuan;
		
		private int _MaTinh;
		
		private EntitySet<Phuong> _Phuongs;
		
		private EntityRef<Tinh> _Tinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaQuanChanging(int value);
    partial void OnMaQuanChanged();
    partial void OnTenQuanChanging(string value);
    partial void OnTenQuanChanged();
    partial void OnMaTinhChanging(int value);
    partial void OnMaTinhChanged();
    #endregion
		
		public Quan()
		{
			this._Phuongs = new EntitySet<Phuong>(new Action<Phuong>(this.attach_Phuongs), new Action<Phuong>(this.detach_Phuongs));
			this._Tinh = default(EntityRef<Tinh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuan", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaQuan
		{
			get
			{
				return this._MaQuan;
			}
			set
			{
				if ((this._MaQuan != value))
				{
					this.OnMaQuanChanging(value);
					this.SendPropertyChanging();
					this._MaQuan = value;
					this.SendPropertyChanged("MaQuan");
					this.OnMaQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuan", DbType="NVarChar(250)")]
		public string TenQuan
		{
			get
			{
				return this._TenQuan;
			}
			set
			{
				if ((this._TenQuan != value))
				{
					this.OnTenQuanChanging(value);
					this.SendPropertyChanging();
					this._TenQuan = value;
					this.SendPropertyChanged("TenQuan");
					this.OnTenQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTinh", DbType="Int NOT NULL")]
		public int MaTinh
		{
			get
			{
				return this._MaTinh;
			}
			set
			{
				if ((this._MaTinh != value))
				{
					if (this._Tinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTinhChanging(value);
					this.SendPropertyChanging();
					this._MaTinh = value;
					this.SendPropertyChanged("MaTinh");
					this.OnMaTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Quan_Phuong", Storage="_Phuongs", ThisKey="MaQuan", OtherKey="MaQuan")]
		public EntitySet<Phuong> Phuongs
		{
			get
			{
				return this._Phuongs;
			}
			set
			{
				this._Phuongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tinh_Quan", Storage="_Tinh", ThisKey="MaTinh", OtherKey="MaTinh", IsForeignKey=true)]
		public Tinh Tinh
		{
			get
			{
				return this._Tinh.Entity;
			}
			set
			{
				Tinh previousValue = this._Tinh.Entity;
				if (((previousValue != value) 
							|| (this._Tinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tinh.Entity = null;
						previousValue.Quans.Remove(this);
					}
					this._Tinh.Entity = value;
					if ((value != null))
					{
						value.Quans.Add(this);
						this._MaTinh = value.MaTinh;
					}
					else
					{
						this._MaTinh = default(int);
					}
					this.SendPropertyChanged("Tinh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Phuongs(Phuong entity)
		{
			this.SendPropertyChanging();
			entity.Quan = this;
		}
		
		private void detach_Phuongs(Phuong entity)
		{
			this.SendPropertyChanging();
			entity.Quan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuocGia")]
	public partial class QuocGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaQuocGia;
		
		private string _TenRutGon;
		
		private string _TenDayDu;
		
		private string _Ma3KyTu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaQuocGiaChanging(string value);
    partial void OnMaQuocGiaChanged();
    partial void OnTenRutGonChanging(string value);
    partial void OnTenRutGonChanged();
    partial void OnTenDayDuChanging(string value);
    partial void OnTenDayDuChanged();
    partial void OnMa3KyTuChanging(string value);
    partial void OnMa3KyTuChanged();
    #endregion
		
		public QuocGia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuocGia", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaQuocGia
		{
			get
			{
				return this._MaQuocGia;
			}
			set
			{
				if ((this._MaQuocGia != value))
				{
					this.OnMaQuocGiaChanging(value);
					this.SendPropertyChanging();
					this._MaQuocGia = value;
					this.SendPropertyChanged("MaQuocGia");
					this.OnMaQuocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenRutGon", DbType="NVarChar(100)")]
		public string TenRutGon
		{
			get
			{
				return this._TenRutGon;
			}
			set
			{
				if ((this._TenRutGon != value))
				{
					this.OnTenRutGonChanging(value);
					this.SendPropertyChanging();
					this._TenRutGon = value;
					this.SendPropertyChanged("TenRutGon");
					this.OnTenRutGonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDayDu", DbType="NVarChar(100)")]
		public string TenDayDu
		{
			get
			{
				return this._TenDayDu;
			}
			set
			{
				if ((this._TenDayDu != value))
				{
					this.OnTenDayDuChanging(value);
					this.SendPropertyChanging();
					this._TenDayDu = value;
					this.SendPropertyChanged("TenDayDu");
					this.OnTenDayDuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma3KyTu", DbType="NVarChar(100)")]
		public string Ma3KyTu
		{
			get
			{
				return this._Ma3KyTu;
			}
			set
			{
				if ((this._Ma3KyTu != value))
				{
					this.OnMa3KyTuChanging(value);
					this.SendPropertyChanging();
					this._Ma3KyTu = value;
					this.SendPropertyChanged("Ma3KyTu");
					this.OnMa3KyTuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenTaiKhoan;
		
		private string _MatKhau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenTaiKhoanChanging(string value);
    partial void OnTenTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    #endregion
		
		public TaiKhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTaiKhoan", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenTaiKhoan
		{
			get
			{
				return this._TenTaiKhoan;
			}
			set
			{
				if ((this._TenTaiKhoan != value))
				{
					this.OnTenTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TenTaiKhoan = value;
					this.SendPropertyChanged("TenTaiKhoan");
					this.OnTenTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tinh")]
	public partial class Tinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTinh;
		
		private string _TenTinh;
		
		private EntitySet<Quan> _Quans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTinhChanging(int value);
    partial void OnMaTinhChanged();
    partial void OnTenTinhChanging(string value);
    partial void OnTenTinhChanged();
    #endregion
		
		public Tinh()
		{
			this._Quans = new EntitySet<Quan>(new Action<Quan>(this.attach_Quans), new Action<Quan>(this.detach_Quans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTinh", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaTinh
		{
			get
			{
				return this._MaTinh;
			}
			set
			{
				if ((this._MaTinh != value))
				{
					this.OnMaTinhChanging(value);
					this.SendPropertyChanging();
					this._MaTinh = value;
					this.SendPropertyChanged("MaTinh");
					this.OnMaTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTinh", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string TenTinh
		{
			get
			{
				return this._TenTinh;
			}
			set
			{
				if ((this._TenTinh != value))
				{
					this.OnTenTinhChanging(value);
					this.SendPropertyChanging();
					this._TenTinh = value;
					this.SendPropertyChanged("TenTinh");
					this.OnTenTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tinh_Quan", Storage="_Quans", ThisKey="MaTinh", OtherKey="MaTinh")]
		public EntitySet<Quan> Quans
		{
			get
			{
				return this._Quans;
			}
			set
			{
				this._Quans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Quans(Quan entity)
		{
			this.SendPropertyChanging();
			entity.Tinh = this;
		}
		
		private void detach_Quans(Quan entity)
		{
			this.SendPropertyChanging();
			entity.Tinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TonGiao")]
	public partial class TonGiao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTonGiao;
		
		private string _TenTonGiao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTonGiaoChanging(int value);
    partial void OnMaTonGiaoChanged();
    partial void OnTenTonGiaoChanging(string value);
    partial void OnTenTonGiaoChanged();
    #endregion
		
		public TonGiao()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTonGiao", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTonGiao
		{
			get
			{
				return this._MaTonGiao;
			}
			set
			{
				if ((this._MaTonGiao != value))
				{
					this.OnMaTonGiaoChanging(value);
					this.SendPropertyChanging();
					this._MaTonGiao = value;
					this.SendPropertyChanged("MaTonGiao");
					this.OnMaTonGiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTonGiao", DbType="NVarChar(40)")]
		public string TenTonGiao
		{
			get
			{
				return this._TenTonGiao;
			}
			set
			{
				if ((this._TenTonGiao != value))
				{
					this.OnTenTonGiaoChanging(value);
					this.SendPropertyChanging();
					this._TenTonGiao = value;
					this.SendPropertyChanged("TenTonGiao");
					this.OnTenTonGiaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class KiemTraDangNhapResult
	{
		
		private string _TENDANGNHAP;
		
		private string _MATKHAU;
		
		public KiemTraDangNhapResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDANGNHAP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TENDANGNHAP
		{
			get
			{
				return this._TENDANGNHAP;
			}
			set
			{
				if ((this._TENDANGNHAP != value))
				{
					this._TENDANGNHAP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this._MATKHAU = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
