<?xml version="1.0" encoding="utf-8"?><Database Name="HoChieu" Class="HoChieuModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=HoChieu;Integrated Security=True" SettingsObjectName="DALDoAnHoChieu.Properties.Settings" SettingsPropertyName="HoChieuConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DangKyHoChieu" Member="DangKyHoChieus">
    <Type Name="DangKyHoChieu">
      <Column Name="MaDangKyMoi" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="QuocGiaNoiSinh" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="Tinh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoCMND" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NgayCapCMND" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NoiCapCMND" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DanToc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TonGiao" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TinhThuongTru" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuanThuongTru" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PhuongThuongTru" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoNhaThuongTru" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TinhTamTru" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhuongTamTru" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuanTamTru" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoNhaTamTru" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgheNghiep" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenCoQuan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChiCoQuan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TenCha" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenMe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinhCha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgaySinhMe" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TenVoChong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinhVoChong" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TrangThai" Member="TrangThais">
    <Type Name="TrangThai">
      <Column Name="MaTrangThai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTrangThai" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DanToc" Member="DanTocs">
    <Type Name="DanToc">
      <Column Name="MaDanToc" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDanToc" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.GioiTinh" Member="GioiTinhs">
    <Type Name="GioiTinh">
      <Column Name="MaGioiTinh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenGioiTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="GioiTinh_HoChieu" Member="HoChieus" ThisKey="MaGioiTinh" OtherKey="GioiTinh" Type="HoChieu" />
    </Type>
  </Table>
  <Table Name="dbo.HoChieu" Member="HoChieus">
    <Type Name="HoChieu">
      <Column Name="SoHoChieu" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuocGia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="QuocTich" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NoiSinh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoCMND" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgayCap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NoiCap" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaDangKy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="GioiTinh_HoChieu" Member="GioiTinh1" ThisKey="GioiTinh" OtherKey="MaGioiTinh" Type="GioiTinh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NgheNghiep" Member="NgheNghieps">
    <Type Name="NgheNghiep">
      <Column Name="MaNgheNghiep" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNgheNghiep" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Phuong" Member="Phuongs">
    <Type Name="Phuong">
      <Column Name="MaPhuong" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenPhuong" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Loai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaQuan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Quan_Phuong" Member="Quan" ThisKey="MaQuan" OtherKey="MaQuan" Type="Quan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Quan" Member="Quans">
    <Type Name="Quan">
      <Column Name="MaQuan" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenQuan" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MaTinh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Quan_Phuong" Member="Phuongs" ThisKey="MaQuan" OtherKey="MaQuan" Type="Phuong" />
      <Association Name="Tinh_Quan" Member="Tinh" ThisKey="MaTinh" OtherKey="MaTinh" Type="Tinh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuocGia" Member="QuocGias">
    <Type Name="QuocGia">
      <Column Name="MaQuocGia" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenRutGon" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TenDayDu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Ma3KyTu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="TenTaiKhoan" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tinh" Member="Tinhs">
    <Type Name="Tinh">
      <Column Name="MaTinh" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTinh" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="Tinh_Quan" Member="Quans" ThisKey="MaTinh" OtherKey="MaTinh" Type="Quan" />
    </Type>
  </Table>
  <Table Name="dbo.TonGiao" Member="TonGiaos">
    <Type Name="TonGiao">
      <Column Name="MaTonGiao" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTonGiao" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.KiemTraDangNhap" Method="KiemTraDangNhap">
    <Parameter Name="username" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="password" Type="System.String" DbType="NVarChar(30)" />
    <ElementType Name="KiemTraDangNhapResult">
      <Column Name="TENDANGNHAP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MATKHAU" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>